### ISSUE TITLE
New ClientInfo

### ISSUE THREAD

**Issue by emilb** [cygni/snakebot-client-js#3]
Please send the following after client connect (replaced with relevant values of course!):

{
    "type": "se.cygni.snake.api.request.ClientInfo",
    "language": "Java",
    "languageVersion": "1.8.0_102",
    "operatingSystem": "Mac OS X",
    "operatingSystemVersion": "10.11.6",
    "clientVersion": "0.16"
  }

**Comment by petalv** [comment]
fixed
